services:
  mssql_server:
    hostname: ${MSSQL_SERVER_HOST}
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SERVER_SA_PASSWORD}
      - MSSQL_SERVER_HOST=${MSSQL_SERVER_HOST}
      - MSSQL_SERVER_SA_PASSWORD=${MSSQL_SERVER_SA_PASSWORD}
      - MSSQL_SERVER_USER=${MSSQL_SERVER_USER}
      - MSSQL_SERVER_PASSWORD=${MSSQL_SERVER_PASSWORD}
      - MSSQL_SERVER_DATABASE=${MSSQL_SERVER_DATABASE}
    ports:
      - ${MSSQL_SERVER_PORT}:1433
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S ${MSSQL_SERVER_HOST} -U sa -P ${MSSQL_SERVER_SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s

#  mssql_server.configurator:
#    image: mcr.microsoft.com/mssql/server:2022-latest
#    environment:
#      - MSSQL_SERVER_HOST=${MSSQL_SERVER_HOST}
#      - MSSQL_SERVER_SA_PASSWORD=${MSSQL_SERVER_SA_PASSWORD}
#      - MSSQL_SERVER_USER=${MSSQL_SERVER_USER}
#      - MSSQL_SERVER_PASSWORD=${MSSQL_SERVER_PASSWORD}
#      - MSSQL_SERVER_DATABASE=${MSSQL_SERVER_DATABASE}
#    volumes:
#      - ./docker/mssql_server/initdb:/container-entrypoint-initdb.d:ro
#    depends_on:
#      mssql_server:
#        condition: service_healthy
#    entrypoint:
#      - docker-entrypoint-initdb.d/init_db.sh

  oracle_server:
    hostname: ${ORACLE_SERVER_HOST}
    image: gvenzl/oracle-free:23-slim-faststart
    environment:
      - ORACLE_PASSWORD=${MSSQL_SERVER_SA_PASSWORD}
      - APP_USER=${ORACLE_SERVER_USER}
      - APP_USER_PASSWORD=${ORACLE_SERVER_PASSWORD}
      - ORACLE_DATABASE=${ORACLE_SERVER_DATABASE}
    ports:
      - ${ORACLE_SERVER_PORT}:1521
    restart: on-failure
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
      start_interval: 5s

  mariadb_server:
    hostname: ${MARIADB_SERVER_HOST}
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD} # Root password for the database
      - MARIADB_DATABASE=${MARIADB_DATABASE}          # Name of the default database
      - MARIADB_USER=${MARIADB_USER}                  # Application user
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}          # Password for the application user
    ports:
      - ${MARIADB_PORT}:3306                          # Maps MariaDB port
    restart: on-failure
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  mysql_server:
    hostname: ${MYSQL_SERVER_HOST}
    image: mysql:latest # Uses the latest official MySQL image
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Root password for the MySQL instance
      - MYSQL_DATABASE=${MYSQL_DATABASE}          # Default database that will be created
      - MYSQL_USER=${MYSQL_USER}                  # Non-root application user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}          # Password for the application user
    ports:
      - ${MYSQL_PORT}:3306                        # Maps MySQL server port to local port
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "${MYSQL_SERVER_HOST}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s

  adminer:
    image: adminer:latest # Latest Adminer image
    ports:
      - ${ADMINER_PORT}:8080 # Maps Adminer port to localhost
    restart: always
