services:
  mssql_server:
    extends:
      file: common.yaml
      service: mssql_server
    hostname: ${MSSQL_SERVER_HOST}
    restart: on-failure
    volumes:
      - mssql_server_data:/var/opt/mssql
      - ./docker/mssql_server/initdb:/container-entrypoint-initdb.d:ro

  oracle_server:
    extends:
      file: common.yaml
      service: oracle_server
    hostname: ${ORACLE_SERVER_HOST}
    restart: on-failure
    volumes:
      - oracle_server_data:/opt/oracle/oradata
      - ./docker/oracle_server/initdb:/container-entrypoint-initdb.d:ro

volumes:
  mssql_server_data:
    driver: local
  oracle_server_data:
    driver: local